

service: server

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: python3.8

functions:
  route:
    handler: handler.route
    events:
      - http:
          path: api/route
          method: get

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    slim: true